// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type ConfigKv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Scope string `json:"scope"`
}

type FileChange struct {
	ID         string  `json:"id"`
	SessionID  string  `json:"session_id"`
	Path       string  `json:"path"`
	Operation  string  `json:"operation"`
	BeforeHash *string `json:"before_hash"`
	AfterHash  *string `json:"after_hash"`
	CreatedAt  int64   `json:"created_at"`
}

type FileRead struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Hash      string `json:"hash"`
	CreatedAt int64  `json:"created_at"`
}

type LedgerEntry struct {
	ID           string  `json:"id"`
	SessionID    string  `json:"session_id"`
	Provider     string  `json:"provider"`
	Model        string  `json:"model"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	CostUsd      float64 `json:"cost_usd"`
	CostInr      float64 `json:"cost_inr"`
	CreatedAt    int64   `json:"created_at"`
}

type Message struct {
	ID          string  `json:"id"`
	SessionID   string  `json:"session_id"`
	Role        string  `json:"role"`
	ContentJson string  `json:"content_json"`
	ParentID    *string `json:"parent_id"`
	CreatedAt   int64   `json:"created_at"`
}

type Session struct {
	ID              string  `json:"id"`
	ProjectPath     string  `json:"project_path"`
	Title           string  `json:"title"`
	Model           string  `json:"model"`
	Agent           string  `json:"agent"`
	CreatedAt       int64   `json:"created_at"`
	UpdatedAt       int64   `json:"updated_at"`
	MessageCount    int64   `json:"message_count"`
	OriginSessionID *string `json:"origin_session_id"`
}
