// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	AppendLedgerEntry(ctx context.Context, arg AppendLedgerEntryParams) (LedgerEntry, error)
	CountMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, id string) error
	GetConfigKV(ctx context.Context, arg GetConfigKVParams) (ConfigKv, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (FileRead, error)
	GetLatestSessionByProjectPath(ctx context.Context, projectPath string) (Session, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionOrigin(ctx context.Context, id string) (*string, error)
	ListFileChangesBySession(ctx context.Context, sessionID string) ([]FileChange, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionPaged(ctx context.Context, arg ListMessagesBySessionPagedParams) ([]Message, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSessionsFiltered(ctx context.Context, arg ListSessionsFilteredParams) ([]Session, error)
	RecordFileChange(ctx context.Context, arg RecordFileChangeParams) (FileChange, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	SetSessionOrigin(ctx context.Context, arg SetSessionOriginParams) error
	SumLedgerCostAndTokensByPeriod(ctx context.Context, arg SumLedgerCostAndTokensByPeriodParams) (SumLedgerCostAndTokensByPeriodRow, error)
	SumLedgerCostByPeriod(ctx context.Context, arg SumLedgerCostByPeriodParams) (SumLedgerCostByPeriodRow, error)
	SumLedgerCostBySession(ctx context.Context, sessionID string) (SumLedgerCostBySessionRow, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpsertConfigKV(ctx context.Context, arg UpsertConfigKVParams) error
}

var _ Querier = (*Queries)(nil)
