// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sqlc

import (
	"context"
)

const appendLedgerEntry = `-- name: AppendLedgerEntry :one
INSERT INTO ledger_entries (
    id, session_id, provider, model, input_tokens, output_tokens, cost_usd, cost_inr, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, provider, model, input_tokens, output_tokens, cost_usd, cost_inr, created_at
`

type AppendLedgerEntryParams struct {
	ID           string  `json:"id"`
	SessionID    string  `json:"session_id"`
	Provider     string  `json:"provider"`
	Model        string  `json:"model"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	CostUsd      float64 `json:"cost_usd"`
	CostInr      float64 `json:"cost_inr"`
	CreatedAt    int64   `json:"created_at"`
}

func (q *Queries) AppendLedgerEntry(ctx context.Context, arg AppendLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRowContext(ctx, appendLedgerEntry,
		arg.ID,
		arg.SessionID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.CostInr,
		arg.CreatedAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Provider,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CostInr,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, session_id, role, content_json, parent_id, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, role, content_json, parent_id, created_at
`

type CreateMessageParams struct {
	ID          string  `json:"id"`
	SessionID   string  `json:"session_id"`
	Role        string  `json:"role"`
	ContentJson string  `json:"content_json"`
	ParentID    *string `json:"parent_id"`
	CreatedAt   int64   `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.ContentJson,
		arg.ParentID,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.ContentJson,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT COUNT(*) FROM messages
WHERE session_id = ?
`

func (q *Queries) CountMessagesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, project_path, title, model, agent, created_at, updated_at, message_count
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, project_path, title, model, agent, created_at, updated_at, message_count
`

type CreateSessionParams struct {
	ID           string `json:"id"`
	ProjectPath  string `json:"project_path"`
	Title        string `json:"title"`
	Model        string `json:"model"`
	Agent        string `json:"agent"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectPath,
		arg.Title,
		arg.Model,
		arg.Agent,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MessageCount,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectPath,
		&i.Title,
		&i.Model,
		&i.Agent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageCount,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionOrigin = `-- name: GetSessionOrigin :one
SELECT origin_session_id FROM sessions
WHERE id = ?
`

func (q *Queries) GetSessionOrigin(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getSessionOrigin, id)
	var origin_session_id *string
	err := row.Scan(&origin_session_id)
	return origin_session_id, err
}

const setSessionOrigin = `-- name: SetSessionOrigin :exec
UPDATE sessions
SET origin_session_id = ?
WHERE id = ?
`

type SetSessionOriginParams struct {
	OriginSessionID *string `json:"origin_session_id"`
	ID              string  `json:"id"`
}

func (q *Queries) SetSessionOrigin(ctx context.Context, arg SetSessionOriginParams) error {
	_, err := q.db.ExecContext(ctx, setSessionOrigin, arg.OriginSessionID, arg.ID)
	return err
}

const getConfigKV = `-- name: GetConfigKV :one
SELECT "key", value, scope FROM config_kv
WHERE scope = ? AND key = ?
`

type GetConfigKVParams struct {
	Scope string `json:"scope"`
	Key   string `json:"key"`
}

func (q *Queries) GetConfigKV(ctx context.Context, arg GetConfigKVParams) (ConfigKv, error) {
	row := q.db.QueryRowContext(ctx, getConfigKV, arg.Scope, arg.Key)
	var i ConfigKv
	err := row.Scan(&i.Key, &i.Value, &i.Scope)
	return i, err
}

const getFileRead = `-- name: GetFileRead :one
SELECT session_id, path, hash, created_at FROM file_reads
WHERE session_id = ? AND path = ?
`

type GetFileReadParams struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

func (q *Queries) GetFileRead(ctx context.Context, arg GetFileReadParams) (FileRead, error) {
	row := q.db.QueryRowContext(ctx, getFileRead, arg.SessionID, arg.Path)
	var i FileRead
	err := row.Scan(
		&i.SessionID,
		&i.Path,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSessionByProjectPath = `-- name: GetLatestSessionByProjectPath :one
SELECT id, project_path, title, model, agent, created_at, updated_at, message_count FROM sessions
WHERE project_path = ?
ORDER BY updated_at DESC, created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionByProjectPath(ctx context.Context, projectPath string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getLatestSessionByProjectPath, projectPath)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectPath,
		&i.Title,
		&i.Model,
		&i.Agent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageCount,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, project_path, title, model, agent, created_at, updated_at, message_count FROM sessions
WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectPath,
		&i.Title,
		&i.Model,
		&i.Agent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageCount,
	)
	return i, err
}

const listFileChangesBySession = `-- name: ListFileChangesBySession :many
SELECT id, session_id, path, operation, before_hash, after_hash, created_at FROM file_changes
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListFileChangesBySession(ctx context.Context, sessionID string) ([]FileChange, error) {
	rows, err := q.db.QueryContext(ctx, listFileChangesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileChange
	for rows.Next() {
		var i FileChange
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Path,
			&i.Operation,
			&i.BeforeHash,
			&i.AfterHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, content_json, parent_id, created_at FROM messages
WHERE session_id = ?
ORDER BY created_at ASC, rowid ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.ContentJson,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionPaged = `-- name: ListMessagesBySessionPaged :many
SELECT id, session_id, role, content_json, parent_id, created_at FROM messages
WHERE session_id = ?
ORDER BY created_at ASC, rowid ASC
LIMIT ? OFFSET ?
`

type ListMessagesBySessionPagedParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListMessagesBySessionPaged(ctx context.Context, arg ListMessagesBySessionPagedParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySessionPaged, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.ContentJson,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, project_path, title, model, agent, created_at, updated_at, message_count FROM sessions
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectPath,
			&i.Title,
			&i.Model,
			&i.Agent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsFiltered = `-- name: ListSessionsFiltered :many
SELECT id, project_path, title, model, agent, created_at, updated_at, message_count FROM sessions
WHERE (CAST(? AS TEXT) = '' OR project_path = CAST(? AS TEXT))
  AND (updated_at >= CAST(? AS INTEGER))
ORDER BY updated_at DESC, created_at DESC, id DESC
LIMIT CASE WHEN CAST(? AS INTEGER) <= 0 THEN -1 ELSE CAST(? AS INTEGER) END
`

type ListSessionsFilteredParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 int64  `json:"column_3"`
	Column4 int64  `json:"column_4"`
	Column5 int64  `json:"column_5"`
}

func (q *Queries) ListSessionsFiltered(ctx context.Context, arg ListSessionsFilteredParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectPath,
			&i.Title,
			&i.Model,
			&i.Agent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFileChange = `-- name: RecordFileChange :one
INSERT INTO file_changes (
    id, session_id, path, operation, before_hash, after_hash, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, path, operation, before_hash, after_hash, created_at
`

type RecordFileChangeParams struct {
	ID         string  `json:"id"`
	SessionID  string  `json:"session_id"`
	Path       string  `json:"path"`
	Operation  string  `json:"operation"`
	BeforeHash *string `json:"before_hash"`
	AfterHash  *string `json:"after_hash"`
	CreatedAt  int64   `json:"created_at"`
}

func (q *Queries) RecordFileChange(ctx context.Context, arg RecordFileChangeParams) (FileChange, error) {
	row := q.db.QueryRowContext(ctx, recordFileChange,
		arg.ID,
		arg.SessionID,
		arg.Path,
		arg.Operation,
		arg.BeforeHash,
		arg.AfterHash,
		arg.CreatedAt,
	)
	var i FileChange
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Path,
		&i.Operation,
		&i.BeforeHash,
		&i.AfterHash,
		&i.CreatedAt,
	)
	return i, err
}

const recordFileRead = `-- name: RecordFileRead :exec
INSERT INTO file_reads (
    session_id, path, hash, created_at
) VALUES (
    ?, ?, ?, ?
)
ON CONFLICT (session_id, path) DO UPDATE
SET hash = excluded.hash,
    created_at = excluded.created_at
`

type RecordFileReadParams struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Hash      string `json:"hash"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) RecordFileRead(ctx context.Context, arg RecordFileReadParams) error {
	_, err := q.db.ExecContext(ctx, recordFileRead,
		arg.SessionID,
		arg.Path,
		arg.Hash,
		arg.CreatedAt,
	)
	return err
}

const sumLedgerCostAndTokensByPeriod = `-- name: SumLedgerCostAndTokensByPeriod :one
SELECT
    COALESCE(SUM(cost_usd), 0.0) AS total_usd,
    COALESCE(SUM(cost_inr), 0.0) AS total_inr,
    COALESCE(SUM(input_tokens), 0) AS total_input,
    COALESCE(SUM(output_tokens), 0) AS total_output,
    COUNT(*) AS call_count
FROM ledger_entries
WHERE created_at >= ? AND created_at <= ?
`

type SumLedgerCostAndTokensByPeriodParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
}

type SumLedgerCostAndTokensByPeriodRow struct {
	TotalUsd    interface{} `json:"total_usd"`
	TotalInr    interface{} `json:"total_inr"`
	TotalInput  interface{} `json:"total_input"`
	TotalOutput interface{} `json:"total_output"`
	CallCount   int64       `json:"call_count"`
}

func (q *Queries) SumLedgerCostAndTokensByPeriod(ctx context.Context, arg SumLedgerCostAndTokensByPeriodParams) (SumLedgerCostAndTokensByPeriodRow, error) {
	row := q.db.QueryRowContext(ctx, sumLedgerCostAndTokensByPeriod, arg.CreatedAt, arg.CreatedAt_2)
	var i SumLedgerCostAndTokensByPeriodRow
	err := row.Scan(
		&i.TotalUsd,
		&i.TotalInr,
		&i.TotalInput,
		&i.TotalOutput,
		&i.CallCount,
	)
	return i, err
}

const sumLedgerCostByPeriod = `-- name: SumLedgerCostByPeriod :one
SELECT
    COALESCE(SUM(cost_usd), 0.0) AS total_usd,
    COALESCE(SUM(cost_inr), 0.0) AS total_inr
FROM ledger_entries
WHERE created_at >= ? AND created_at <= ?
`

type SumLedgerCostByPeriodParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
}

type SumLedgerCostByPeriodRow struct {
	TotalUsd interface{} `json:"total_usd"`
	TotalInr interface{} `json:"total_inr"`
}

func (q *Queries) SumLedgerCostByPeriod(ctx context.Context, arg SumLedgerCostByPeriodParams) (SumLedgerCostByPeriodRow, error) {
	row := q.db.QueryRowContext(ctx, sumLedgerCostByPeriod, arg.CreatedAt, arg.CreatedAt_2)
	var i SumLedgerCostByPeriodRow
	err := row.Scan(&i.TotalUsd, &i.TotalInr)
	return i, err
}

const sumLedgerCostBySession = `-- name: SumLedgerCostBySession :one
SELECT
    COALESCE(SUM(cost_usd), 0.0) AS total_usd,
    COALESCE(SUM(cost_inr), 0.0) AS total_inr,
    COALESCE(SUM(input_tokens), 0) AS total_input,
    COALESCE(SUM(output_tokens), 0) AS total_output,
    COUNT(*) AS call_count
FROM ledger_entries
WHERE session_id = ?
`

type SumLedgerCostBySessionRow struct {
	TotalUsd    interface{} `json:"total_usd"`
	TotalInr    interface{} `json:"total_inr"`
	TotalInput  interface{} `json:"total_input"`
	TotalOutput interface{} `json:"total_output"`
	CallCount   int64       `json:"call_count"`
}

func (q *Queries) SumLedgerCostBySession(ctx context.Context, sessionID string) (SumLedgerCostBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, sumLedgerCostBySession, sessionID)
	var i SumLedgerCostBySessionRow
	err := row.Scan(
		&i.TotalUsd,
		&i.TotalInr,
		&i.TotalInput,
		&i.TotalOutput,
		&i.CallCount,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET project_path = ?,
    title = ?,
    model = ?,
    agent = ?,
    updated_at = ?,
    message_count = ?
WHERE id = ?
RETURNING id, project_path, title, model, agent, created_at, updated_at, message_count
`

type UpdateSessionParams struct {
	ProjectPath  string `json:"project_path"`
	Title        string `json:"title"`
	Model        string `json:"model"`
	Agent        string `json:"agent"`
	UpdatedAt    int64  `json:"updated_at"`
	MessageCount int64  `json:"message_count"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.ProjectPath,
		arg.Title,
		arg.Model,
		arg.Agent,
		arg.UpdatedAt,
		arg.MessageCount,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectPath,
		&i.Title,
		&i.Model,
		&i.Agent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageCount,
	)
	return i, err
}

const upsertConfigKV = `-- name: UpsertConfigKV :exec
INSERT INTO config_kv (
    key, value, scope
) VALUES (
    ?, ?, ?
)
ON CONFLICT (scope, key) DO UPDATE
SET value = excluded.value
`

type UpsertConfigKVParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Scope string `json:"scope"`
}

func (q *Queries) UpsertConfigKV(ctx context.Context, arg UpsertConfigKVParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfigKV, arg.Key, arg.Value, arg.Scope)
	return err
}
