package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

// newCompletionCmd builds the `bharatcode completion` command, which
// emits a shell completion script for bash, zsh, or fish to stdout.
// The user installs it by sourcing the output, e.g.
//
//	source <(bharatcode completion zsh)
//
// The script is generated by cobra from the live command tree, so it
// stays in sync with the registered subcommands and flags.
func newCompletionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "completion [bash|zsh|fish]",
		Short: "Generate a shell completion script",
		Long: `Generate a shell completion script for bharatcode.

Load the completions into the current shell:

  Bash:
    source <(bharatcode completion bash)

  Zsh:
    source <(bharatcode completion zsh)

  Fish:
    bharatcode completion fish | source`,
		Args:                  cobra.ExactArgs(1),
		ValidArgs:             []string{"bash", "zsh", "fish"},
		DisableFlagsInUseLine: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()
			switch args[0] {
			case "bash":
				if err := cmd.Root().GenBashCompletion(out); err != nil {
					return fmt.Errorf("generating bash completion: %w", err)
				}
			case "zsh":
				if err := cmd.Root().GenZshCompletion(out); err != nil {
					return fmt.Errorf("generating zsh completion: %w", err)
				}
			case "fish":
				if err := cmd.Root().GenFishCompletion(out, true); err != nil {
					return fmt.Errorf("generating fish completion: %w", err)
				}
			default:
				return fmt.Errorf("unsupported shell %q: choose bash, zsh, or fish", args[0])
			}
			return nil
		},
	}
}
