// Package db owns BharatCode's SQLite persistence layer. The schema is
// defined as SQL migrations under internal/db/migrations/ and
// query code is generated by sqlc into internal/db/sqlc/.
package db

import (
	"context"
	"fmt"
)

// Backup writes a consistent, standalone copy of the database to
// destPath using SQLite's VACUUM INTO, which is the safe online-backup
// primitive: it snapshots the committed view of the database (including
// any data still living in the -wal file) into a freshly compacted file
// without blocking the source. The resulting file is a complete
// BharatCode database — schema, migration-tracking table, and all rows —
// that can be opened directly with Open, so restoring is simply
// Open(ctx, destPath) (see Restore).
//
// destPath must not already exist as a non-empty file; VACUUM INTO
// refuses to write over existing data and Backup surfaces that error
// rather than silently clobbering it. The parent directory must exist.
//
// Backup returns ErrClosed if called after Close. It mirrors Maintain's
// locking: the closed flag is checked under the mutex, which is then
// released for the duration of the copy.
func (db *DB) Backup(ctx context.Context, destPath string) error {
	db.mu.Lock()
	if db.closed {
		db.mu.Unlock()
		return ErrClosed
	}
	db.mu.Unlock()

	if destPath == "" {
		return fmt.Errorf("backing up database: destination path is empty")
	}

	if _, err := db.ExecContext(ctx, "VACUUM INTO ?;", destPath); err != nil {
		return fmt.Errorf("backing up database to %q: %w", destPath, err)
	}

	return nil
}

// Restore opens a database previously produced by Backup as a new,
// ready-to-use *DB. Because a backup is a complete standalone BharatCode
// database, restoring is just opening it: Restore re-applies the
// configured pragmas and runs migrations (a no-op against an up-to-date
// backup, since VACUUM INTO copies the migration-tracking table) and
// returns a handle whose rows and queries match the source at backup
// time. The caller owns the returned *DB and must Close it.
func Restore(ctx context.Context, backupPath string) (*DB, error) {
	d, err := Open(ctx, backupPath)
	if err != nil {
		return nil, fmt.Errorf("restoring database from %q: %w", backupPath, err)
	}
	return d, nil
}
