// Package db owns BharatCode's SQLite persistence layer. The schema is
// defined as SQL migrations under internal/db/migrations/ and
// query code is generated by sqlc into internal/db/sqlc/.
package db

import (
	"database/sql"
	"errors"
	"fmt"
	"sync"

	sqlc "github.com/arbazkhan971/bharatcode/internal/db/sqlc"
)

// DB is a handle to BharatCode's persistent store. It wraps the
// underlying *sql.DB and exposes a *sqlc.Queries for generated
// type-safe access. The zero value is not usable; callers must call
// Open.
type DB struct {
	*sql.DB
	Queries *sqlc.Queries
	path    string

	mu     sync.Mutex
	closed bool
}

// ErrClosed is returned by methods on a *DB after Close has been called.
var ErrClosed = errors.New("db: connection closed")

// Close closes the underlying *sql.DB. Subsequent calls to any method
// on the returned *DB return ErrClosed. Close is idempotent.
func (db *DB) Close() error {
	db.mu.Lock()
	defer db.mu.Unlock()
	if db.closed {
		return nil
	}
	db.closed = true

	if err := releasePool(db.path); err != nil {
		return fmt.Errorf("closing db: %w", err)
	}

	return nil
}

// Path returns the absolute filesystem path of the database file.
func (db *DB) Path() string {
	return db.path
}
