// Package db owns BharatCode's SQLite persistence layer. The schema is
// defined as SQL migrations under internal/db/migrations/ and
// query code is generated by sqlc into internal/db/sqlc/.
package db

import (
	"context"
	"fmt"
)

// Maintain keeps the SQLite database file healthy and compact over long
// use. It verifies on-disk integrity with PRAGMA integrity_check, then
// reclaims free pages and defragments the file with VACUUM, and finally
// refreshes the query planner's statistics with ANALYZE. Running it
// periodically prevents the file from bloating after large deletes and
// surfaces corruption early.
//
// Maintain returns ErrClosed if called after Close. If the integrity
// check reports anything other than "ok", Maintain returns an error
// describing the problem and does not run VACUUM, leaving the file
// untouched for inspection.
func (db *DB) Maintain(ctx context.Context) error {
	db.mu.Lock()
	if db.closed {
		db.mu.Unlock()
		return ErrClosed
	}
	db.mu.Unlock()

	if err := db.IntegrityCheck(ctx); err != nil {
		return err
	}

	if _, err := db.ExecContext(ctx, "VACUUM;"); err != nil {
		return fmt.Errorf("vacuuming database: %w", err)
	}

	if _, err := db.ExecContext(ctx, "ANALYZE;"); err != nil {
		return fmt.Errorf("analyzing database: %w", err)
	}

	return nil
}

// IntegrityCheck runs PRAGMA integrity_check and returns nil only when
// SQLite reports the database is consistent (the single result row is
// "ok"). Any other result indicates corruption and is returned as an
// error containing SQLite's diagnostic. IntegrityCheck returns ErrClosed
// if called after Close.
func (db *DB) IntegrityCheck(ctx context.Context) error {
	db.mu.Lock()
	if db.closed {
		db.mu.Unlock()
		return ErrClosed
	}
	db.mu.Unlock()

	var result string
	if err := db.QueryRowContext(ctx, "PRAGMA integrity_check;").Scan(&result); err != nil {
		return fmt.Errorf("running integrity check: %w", err)
	}
	if result != "ok" {
		return fmt.Errorf("database integrity check failed: %s", result)
	}
	return nil
}
