// Package db owns BharatCode's SQLite persistence layer. The schema is
// defined as SQL migrations under internal/db/migrations/ and
// query code is generated by sqlc into internal/db/sqlc/.
package db

import (
	"bufio"
	"context"
	"embed"
	"fmt"
	"io/fs"
	"sort"
	"strings"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// Migrate applies any pending migrations from the embedded migrations
// filesystem. It is called automatically by Open and exposed for tests
// and the `bharatcode migrate` CLI command. Migrate is idempotent:
// calling it twice on the same database is a no-op on the second call.
func (db *DB) Migrate(ctx context.Context) error {
	db.mu.Lock()
	if db.closed {
		db.mu.Unlock()
		return ErrClosed
	}
	db.mu.Unlock()

	if _, err := db.ExecContext(ctx, `
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000)
);`); err != nil {
		return fmt.Errorf("ensuring schema migrations table: %w", err)
	}

	files, err := migrationFiles(migrationsFS)
	if err != nil {
		return err
	}
	for _, file := range files {
		if err := db.applyMigration(ctx, file); err != nil {
			return err
		}
	}

	return nil
}

func migrationFiles(fsys fs.FS) ([]string, error) {
	entries, err := fs.ReadDir(fsys, "migrations")
	if err != nil {
		return nil, fmt.Errorf("reading migrations directory: %w", err)
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".sql") {
			continue
		}
		files = append(files, "migrations/"+entry.Name())
	}
	sort.Strings(files)
	return files, nil
}

func (db *DB) applyMigration(ctx context.Context, file string) error {
	var exists int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM schema_migrations WHERE version = ?", file).Scan(&exists); err != nil {
		return fmt.Errorf("checking migration %s: %w", file, err)
	}
	if exists > 0 {
		return nil
	}

	raw, err := fs.ReadFile(migrationsFS, file)
	if err != nil {
		return fmt.Errorf("reading migration %s: %w", file, err)
	}
	upSQL, err := upMigrationSQL(string(raw))
	if err != nil {
		return fmt.Errorf("parsing migration %s: %w", file, err)
	}

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("beginning migration %s: %w", file, err)
	}
	defer func() {
		_ = tx.Rollback()
	}()

	if strings.TrimSpace(upSQL) != "" {
		if _, err := tx.ExecContext(ctx, upSQL); err != nil {
			return fmt.Errorf("executing migration %s: %w", file, err)
		}
	}
	if _, err := tx.ExecContext(ctx, "INSERT INTO schema_migrations(version) VALUES (?)", file); err != nil {
		return fmt.Errorf("recording migration %s: %w", file, err)
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("committing migration %s: %w", file, err)
	}
	return nil
}

func upMigrationSQL(raw string) (string, error) {
	scanner := bufio.NewScanner(strings.NewReader(raw))
	var lines []string
	inUp := false
	seenUp := false
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		switch trimmed {
		case "-- +goose Up":
			inUp = true
			seenUp = true
			continue
		case "-- +goose Down":
			inUp = false
			continue
		case "-- +goose StatementBegin", "-- +goose StatementEnd":
			continue
		}
		if inUp {
			lines = append(lines, line)
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scanning migration: %w", err)
	}
	if !seenUp {
		return "", fmt.Errorf("missing up migration section")
	}
	return strings.TrimSpace(strings.Join(lines, "\n")), nil
}
