// Package db owns BharatCode's SQLite persistence layer. The schema is
// defined as SQL migrations under internal/db/migrations/ and
// query code is generated by sqlc into internal/db/sqlc/.
package db

import (
	"context"
	"database/sql"
	"fmt"
	"path/filepath"
	"sync"

	sqlc "github.com/arbazkhan971/bharatcode/internal/db/sqlc"
	"github.com/arbazkhan971/bharatcode/internal/util"
	"github.com/arbazkhan971/bharatcode/internal/util/fsext"

	_ "modernc.org/sqlite"
)

type sharedPool struct {
	db       *sql.DB
	refCount int
}

var (
	pools   = make(map[string]*sharedPool)
	poolsMu sync.Mutex
)

// Open opens (or creates) the SQLite database at path, applies pending
// migrations, configures pragmas (WAL, foreign keys, busy_timeout),
// and returns a ready-to-use *DB. The parent directory is created with
// 0o755 if it does not exist. Open is safe to call concurrently for
// different paths; concurrent calls for the same path are serialized
// internally and return distinct *DB values sharing the underlying
// *sql.DB connection pool.
func Open(ctx context.Context, path string) (*DB, error) {
	expanded := util.ExpandPath(path)
	absPath, err := filepath.Abs(expanded)
	if err != nil {
		return nil, fmt.Errorf("resolving path %q: %w", path, err)
	}

	dir := filepath.Dir(absPath)
	if err := fsext.EnsureDir(dir, 0o755); err != nil {
		return nil, fmt.Errorf("ensuring directory %q: %w", dir, err)
	}

	poolsMu.Lock()
	defer poolsMu.Unlock()

	p, ok := pools[absPath]
	if !ok {
		dbConn, err := sql.Open("sqlite", absPath)
		if err != nil {
			return nil, fmt.Errorf("opening SQLite connection: %w", err)
		}

		dbConn.SetMaxOpenConns(1)

		if err := setupPragmas(ctx, dbConn); err != nil {
			dbConn.Close()
			return nil, fmt.Errorf("setting up SQLite pragmas: %w", err)
		}

		if err := dbConn.PingContext(ctx); err != nil {
			dbConn.Close()
			return nil, fmt.Errorf("pinging SQLite database: %w", err)
		}

		p = &sharedPool{
			db:       dbConn,
			refCount: 0,
		}
		pools[absPath] = p
	}

	p.refCount++

	dbWrap := &DB{
		DB:   p.db,
		path: absPath,
	}

	dbWrap.Queries = sqlc.New(&pragmaDBTX{db: p.db})

	if err := dbWrap.Migrate(ctx); err != nil {
		p.refCount--
		if p.refCount <= 0 {
			delete(pools, absPath)
			p.db.Close()
		}
		return nil, fmt.Errorf("running initial migrations: %w", err)
	}

	return dbWrap, nil
}

// releasePool decrements reference count and closes the pool if no handles remain.
func releasePool(path string) error {
	poolsMu.Lock()
	defer poolsMu.Unlock()

	p, ok := pools[path]
	if !ok {
		return nil
	}
	p.refCount--
	if p.refCount <= 0 {
		delete(pools, path)
		if err := p.db.Close(); err != nil {
			return fmt.Errorf("closing shared database pool: %w", err)
		}
	}
	return nil
}

func setupPragmas(ctx context.Context, db *sql.DB) error {
	pragmas := []string{
		"PRAGMA journal_mode = WAL;",
		"PRAGMA foreign_keys = ON;",
		"PRAGMA busy_timeout = 5000;",
		"PRAGMA synchronous = NORMAL;",
		"PRAGMA temp_store = MEMORY;",
	}
	for _, pragma := range pragmas {
		if _, err := db.ExecContext(ctx, pragma); err != nil {
			return fmt.Errorf("executing pragma %q: %w", pragma, err)
		}
	}
	return nil
}

type pragmaDBTX struct {
	db *sql.DB
}

func (p *pragmaDBTX) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	if _, err := p.db.ExecContext(ctx, "PRAGMA foreign_keys = ON;"); err != nil {
		return nil, fmt.Errorf("asserting foreign keys: %w", err)
	}
	return p.db.ExecContext(ctx, query, args...)
}

func (p *pragmaDBTX) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	if _, err := p.db.ExecContext(ctx, "PRAGMA foreign_keys = ON;"); err != nil {
		return nil, fmt.Errorf("asserting foreign keys: %w", err)
	}
	return p.db.PrepareContext(ctx, query)
}

func (p *pragmaDBTX) QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {
	if _, err := p.db.ExecContext(ctx, "PRAGMA foreign_keys = ON;"); err != nil {
		return nil, fmt.Errorf("asserting foreign keys: %w", err)
	}
	return p.db.QueryContext(ctx, query, args...)
}

func (p *pragmaDBTX) QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row {
	_, _ = p.db.ExecContext(ctx, "PRAGMA foreign_keys = ON;")
	return p.db.QueryRowContext(ctx, query, args...)
}
